// HtmlTemplates.h
#ifndef HTML_TEMPLATES_H
#define HTML_TEMPLATES_H

#include <string.h>

// ============================================================
// PAGINA PRINCIPALE (CONTROLLO MOTORE DC 12V)
// ============================================================

/*
// ============================================================
// VECCHIA PAGINA PER SERVO (commentata)
// ============================================================
static const char* getServoPage(void) {
    return 
        "<!DOCTYPE html>"
        "<html>"
        "<head><title>Controllo Servo 12V</title>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        "<style>"
        "body { font-family: Arial, 'Microsoft YaHei', sans-serif; text-align: center; margin: 20px; background: #eef2f6; }"
        ".container { max-width: 400px; margin: auto; background: #fff; padding: 20px; border-radius: 15px; box-shadow: 0 4px 14px rgba(0,0,0,0.08); }"
        ".slider { width: 100%; }"
        "button { font-size: 24px; padding: 12px 24px; margin: 10px; border-radius: 10px; border: none; cursor: pointer; }"
        ".btn-0 { background: #ff6b6b; color: white; }"
        ".btn-90 { background: #feca57; color: white; }"
        ".btn-180 { background: #48dbfb; color: white; }"
        ".angle { font-size: 48px; font-weight: bold; color: #2d3436; }"
        ".ip { font-size: 14px; color: #636e72; margin-top: 10px; }"
        ".status { font-size: 14px; color: #2d3436; margin-top: 10px; }"
        "</style>"
        "</head>"
        "<body>"
        "<div class='container'>"
        "<h1>🎯 Controllo Servo 12V</h1>"
        "<p class='ip'>🌐 IP: 192.168.4.1</p>"
        "<p class='status' id='status'>Stato: Pronto</p>"
        "<p class='angle' id='angleDisplay'>90°</p>"
        "<input type='range' min='0' max='180' value='90' class='slider' id='slider'"
        " oninput=\"sendAngle(this.value)\">"
        "<br>"
        "<button class='btn-0' onclick=\"sendAngle(0)\">0°</button>"
        "<button class='btn-90' onclick=\"sendAngle(90)\">90°</button>"
        "<button class='btn-180' onclick=\"sendAngle(180)\">180°</button>"
        "</div>"
        "<script>"
        "function sendAngle(angle) {"
        "    document.getElementById('angleDisplay').textContent = angle + '°';"
        "    document.getElementById('slider').value = angle;"
        "    document.getElementById('status').textContent = 'Stato: Invio...';"
        "    fetch('/servo?angle=' + angle)"
        "        .then(response => response.text())"
        "        .then(data => {"
        "            document.getElementById('status').textContent = 'Stato: ' + data;"
        "        })"
        "        .catch(() => {"
        "            document.getElementById('status').textContent = 'Stato: Errore!';"
        "        });"
        "}"
        "</script>"
        "</body>"
        "</html>";
}
*/

// ============================================================
// NUOVA PAGINA PER MOTORE DC 12V
// ============================================================
// HtmlTemplates.h
static const char* getMotorPage(void) {
    return 
        "<!DOCTYPE html>"
        "<html lang='it'>"
        "<head>"
        "    <meta charset='UTF-8'>"
        "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        "    <title>Controllo Motore 12V</title>"
        "    <style>"
        "        * { box-sizing: border-box; margin: 0; padding: 0; }"
        "        body {"
        "            font-family: 'Segoe UI', Arial, sans-serif;"
        "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
        "            min-height: 100vh;"
        "            display: flex;"
        "            justify-content: center;"
        "            align-items: center;"
        "            padding: 20px;"
        "        }"
        "        .container {"
        "            background: white;"
        "            border-radius: 20px;"
        "            padding: 30px;"
        "            max-width: 450px;"
        "            width: 100%;"
        "            box-shadow: 0 20px 60px rgba(0,0,0,0.3);"
        "        }"
        "        h1 {"
        "            text-align: center;"
        "            color: #2d3436;"
        "            font-size: 26px;"
        "            margin-bottom: 5px;"
        "        }"
        "        .subtitle {"
        "            text-align: center;"
        "            color: #636e72;"
        "            font-size: 14px;"
        "            margin-bottom: 20px;"
        "        }"
        "        .status-box {"
        "            background: #f8f9fa;"
        "            border-radius: 12px;"
        "            padding: 12px;"
        "            text-align: center;"
        "            margin-bottom: 20px;"
        "            border-left: 4px solid #00b894;"
        "        }"
        "        .status-text {"
        "            font-weight: 600;"
        "            color: #2d3436;"
        "        }"
        "        .status-ok { color: #00b894; }"
        "        .status-error { color: #e17055; }"
        "        .speed-display {"
        "            text-align: center;"
        "            font-size: 48px;"
        "            font-weight: 700;"
        "            color: #2d3436;"
        "            margin: 10px 0;"
        "        }"
        "        .speed-label {"
        "            text-align: center;"
        "            color: #636e72;"
        "            font-size: 14px;"
        "            margin-bottom: 15px;"
        "        }"
        "        .slider-container {"
        "            margin: 15px 0 20px 0;"
        "        }"
        "        input[type='range'] {"
        "            -webkit-appearance: none;"
        "            width: 100%;"
        "            height: 8px;"
        "            border-radius: 5px;"
        "            background: linear-gradient(to right, #00b894, #00cec9);"
        "            outline: none;"
        "        }"
        "        input[type='range']::-webkit-slider-thumb {"
        "            -webkit-appearance: none;"
        "            appearance: none;"
        "            width: 24px;"
        "            height: 24px;"
        "            border-radius: 50%;"
        "            background: #6c5ce7;"
        "            cursor: pointer;"
        "            border: 3px solid white;"
        "            box-shadow: 0 2px 8px rgba(0,0,0,0.2);"
        "        }"
        "        .button-group {"
        "            display: grid;"
        "            grid-template-columns: 1fr 1fr 1fr;"
        "            gap: 10px;"
        "            margin: 15px 0;"
        "        }"
        "        .btn {"
        "            padding: 14px 10px;"
        "            border: none;"
        "            border-radius: 12px;"
        "            font-size: 16px;"
        "            font-weight: 600;"
        "            cursor: pointer;"
        "            transition: all 0.3s ease;"
        "            color: white;"
        "        }"
        "        .btn:hover {"
        "            transform: translateY(-2px);"
        "            box-shadow: 0 6px 20px rgba(0,0,0,0.2);"
        "        }"
        "        .btn:active { transform: scale(0.95); }"
        "        .btn-avanti { background: #00b894; }"
        "        .btn-avanti:hover { background: #00a381; }"
        "        .btn-indietro { background: #e17055; }"
        "        .btn-indietro:hover { background: #d63031; }"
        "        .btn-stop { background: #fdcb6e; color: #2d3436; }"
        "        .btn-stop:hover { background: #f9ca24; }"
        "        .btn-freno { background: #6c5ce7; }"
        "        .btn-freno:hover { background: #5f3dc4; }"
        "        .btn-lento { background: #74b9ff; }"
        "        .btn-medio { background: #0984e3; }"
        "        .btn-massimo { background: #d63031; }"
        "        .btn-small {"
        "            padding: 10px 8px;"
        "            font-size: 13px;"
        "        }"
        "        .speed-presets {"
        "            display: grid;"
        "            grid-template-columns: 1fr 1fr 1fr;"
        "            gap: 10px;"
        "            margin: 10px 0 5px 0;"
        "        }"
        "        .ip-info {"
        "            text-align: center;"
        "            color: #b2bec3;"
        "            font-size: 12px;"
        "            margin-top: 15px;"
        "        }"
        "        .footer {"
        "            text-align: center;"
        "            color: #b2bec3;"
        "            font-size: 11px;"
        "            margin-top: 15px;"
        "        }"
        "        /* Mobile */"
        "        @media (max-width: 480px) {"
        "            .container { padding: 20px; }"
        "            .button-group { grid-template-columns: 1fr 1fr 1fr; gap: 8px; }"
        "            .speed-presets { grid-template-columns: 1fr 1fr 1fr; gap: 8px; }"
        "            .btn { padding: 12px 8px; font-size: 14px; }"
        "            .speed-display { font-size: 36px; }"
        "        }"
        "    </style>"
        "</head>"
        "<body>"
        "<div class='container'>"
        "    <h1>⚡ Controllo Motore</h1>"
        "    <p class='subtitle'>DC 12V &bull; ESP32-C3</p>"
        ""
        "    <div class='status-box'>"
        "        <span class='status-text'>📡 Stato: </span>"
        "        <span class='status-ok' id='statusText'>Pronto</span>"
        "    </div>"
        ""
        "    <div class='speed-display' id='speedDisplay'>0</div>"
        "    <div class='speed-label'>Velocità: <span id='speedLabel'>0</span> / 255</div>"
        ""
        "    <div class='slider-container'>"
        "        <input type='range' min='0' max='255' value='0' class='slider' id='slider'>"
        "    </div>"
        ""
        "    <div class='button-group'>"
        "        <button class='btn btn-avanti' onclick='sendCommand(\"avanti\", 128)'>▶ Avanti</button>"
        "        <button class='btn btn-indietro' onclick='sendCommand(\"indietro\", 128)'>◀ Indietro</button>"
        "        <button class='btn btn-stop' onclick='sendCommand(\"stop\", 0)'>⏹ Stop</button>"
        "    </div>"
        ""
        "    <div class='speed-presets'>"
        "        <button class='btn btn-lento btn-small' onclick='sendCommand(\"avanti\", 64)'>🐢 Lento</button>"
        "        <button class='btn btn-medio btn-small' onclick='sendCommand(\"avanti\", 128)'>⚡ Medio</button>"
        "        <button class='btn btn-massimo btn-small' onclick='sendCommand(\"avanti\", 255)'>🚀 Massimo</button>"
        "    </div>"
        ""
        "    <p class='ip-info'>🌐 IP: 192.168.4.1</p>"
        "    <p class='footer'>Controllo motore DC 12V &bull; ESP32-C3</p>"
        "</div>"
        "<script>"
        "    function sendCommand(direction, speed) {"
        "        document.getElementById('speedDisplay').textContent = speed;"
        "        document.getElementById('speedLabel').textContent = speed;"
        "        document.getElementById('slider').value = speed;"
        "        document.getElementById('statusText').textContent = 'Invio...';"
        "        document.getElementById('statusText').className = 'status-text';"
        ""
        "        let dir = 1;"
        "        let brake = 0;"
        "        if (direction === 'indietro') { dir = 0; }"
        "        if (direction === 'stop') { speed = 0; brake = 1; }"
        ""
        "        fetch('/motor?speed=' + speed + '&dir=' + dir + '&brake=' + brake)"
        "            .then(response => response.text())"
        "            .then(data => {"
        "                document.getElementById('statusText').textContent = 'OK: ' + data;"
        "                document.getElementById('statusText').className = 'status-ok';"
        "            })"
        "            .catch(() => {"
        "                document.getElementById('statusText').textContent = 'Errore!';"
        "                document.getElementById('statusText').className = 'status-error';"
        "            });"
        "    }"
        ""
        "    // Slider"
        "    document.getElementById('slider').oninput = function() {"
        "        let value = this.value;"
        "        document.getElementById('speedDisplay').textContent = value;"
        "        document.getElementById('speedLabel').textContent = value;"
        "        document.getElementById('statusText').textContent = 'Slider...';"
        "        fetch('/motor?speed=' + value + '&dir=1&brake=0');"
        "    };"
        "</script>"
        "</body>"
        "</html>";
}

#endif